// automatically generated parameter types
// make sure you change them where needed
//=========================================
  void __dabnew_MOD_change_package(int *i);
  void __dabnew_MOD_daini(int *no, int *nv, int *iunit);
  void __dabnew_MOD_dallsta(int *ldanow);
  void __dabnew_MOD_daallno1(int *ic, char *ccc);
  void __dabnew_MOD_daall(int *ic, int *l, char *ccc, int *no, int *nv);
  void __dabnew_MOD_daall1(int *ic, char *ccc, int *no, int *nv);
  void __dabnew_MOD_daall0(int *ic);
  void __dabnew_MOD_dadal(int *idal, int *l);
  void __dabnew_MOD_dadal1(int *idal);
  void __dabnew_MOD_count_da(int *n);
  void __dabnew_MOD_davar(int *ina, double *ckon, int *i);
  void __dabnew_MOD_dacon(int *ina, double *ckon);
  void __dabnew_MOD_danot(int *not);
  void __dabnew_MOD_daeps(double *deps);
  void __dabnew_MOD_dapek(int *ina, int *jv, double *cjj);
  void __dabnew_MOD_dapok(int *ina, int *jv, double *cjj);
  void __dabnew_MOD_daclr(int *inc);
  void __dabnew_MOD_dacop(int *ina, int *inb);
  void __dabnew_MOD_daadd(int *ina, int *inb, int *inc);
  void __dabnew_MOD_datrunc(int *ina, int *io, int *inb);
  void __dabnew_MOD_dasub(int *ina, int *inb, int *inc);
  void __dabnew_MOD_damul(int *ina, int *inb, int *inc);
  void __dabnew_MOD_damult(int *ina, int *inb, int *inc);
  void __dabnew_MOD_dadiv(int *ina, int *inb, int *inc);
  void __dabnew_MOD_dasqr(int *ina, int *inc);
  void __dabnew_MOD_dasqrt(int *ina, int *inc);
  void __dabnew_MOD_dacad(int *ina, double *ckon, int *inb);
  void __dabnew_MOD_dacsu(int *ina, double *ckon, int *inb);
  void __dabnew_MOD_dasuc(int *ina, double *ckon, int *inb);
  void __dabnew_MOD_dacmu(int *ina, double *ckon, int *inc);
  void __dabnew_MOD_dacmut(int *ina, double *ckon, int *inb);
  void __dabnew_MOD_dacdi(int *ina, double *ckon, int *inb);
  void __dabnew_MOD_dadic(int *ina, double *ckon, int *inc);
  void __dabnew_MOD_dacma(int *ina, int *inb, double *bfac, int *inc);
  void __dabnew_MOD_dalin(int *ina, double *afac, int *inb, double *bfac, int *inc);
  void __dabnew_MOD_dalint(int *ina, double *afac, int *inb, double *bfac, int *inc);
  void __dabnew_MOD_dafun(char *cf, int *ina, int *inc);
  void __dabnew_MOD_dafunt(char *cf, int *ina, int *inc);
  void __dabnew_MOD_daabs(int *ina, double *anorm);
  void __dabnew_MOD_dacct(int *ma, int *ia, int *mb, int *ib, int *mc, int *ic);
  void __dabnew_MOD_dacctt(int *mb, int *ib, int *mc, int *ic, int *ma, int *ia);
  void __dabnew_MOD_mtree(int *mb, int *ib, int *mc, int *ic);
  void __dabnew_MOD_ppushprint(int *mc, int *ic, int *mf, int *jc, char *line);
  void __dabnew_MOD_ppushstore(int *mc, int *nd2, double *coef, int *ml, int *mv);
  void __dabnew_MOD_ppushGETN(int *mc, int *ND2, int *ntot);
  void __dabnew_MOD_ppush(int *mc, int *ic, int *xi, int *xf);
  void __dabnew_MOD_ppush1(int *mc, double *xi, double *xf);
  void __dabnew_MOD_dainv(int *ma, int *ia, int *mb, int *ib);
  void __dabnew_MOD_dainvt(int *ma, int *ia, int *mb, int *ib);
  void __dabnew_MOD_dapin(int *ma, int *ia, int *mb, int *ib, int *jx);
  void __dabnew_MOD_dapint(int *ma, int *ia, int *mb, int *ib, int *jind);
  void __dabnew_MOD_dader(int *idif, int *ina, int *inc);
  void __dabnew_MOD_dadert(int *idif, int *ina, int *inc);
  void __dabnew_MOD_dacfuR(int *ina, int *fun, int *inc);
  void __dabnew_MOD_dacfuRt(int *ina, int *fun, int *inc);
  // void __dabnew_MOD_dacfu(int *ina, int *fun, int *inc);
  // void __dabnew_MOD_dacfuI(int *ina, int *fun, int *inc);
  // void __dabnew_MOD_dacfuIt(int *ina, int *fun, int *inc);
  // void __dabnew_MOD_dacfut(int *ina, int *fun, int *inc);
  void __dabnew_MOD_dapri(int *ina, int *iunit);
  void __dabnew_MOD_dapri77(int *ina, int *iunit);
  void __dabnew_MOD_dashift(int *ina, int *inc, int *ishift);
  void __dabnew_MOD_darea(int *ina, int *iunit);
  void __dabnew_MOD_darea77(int *ina, int *iunit);
  void __dabnew_MOD_dainf(int *inc, int *inoc, int *invc, int *ipoc, int *ilmc, int *illc);
  void __dabnew_MOD_dapac(int *inc);
  void __dabnew_MOD_dachk(int *ina, int *inoa, int *inva, int *inb, int *inob, int *invb, int *inc, int *inoc, int *invc);
  void __dabnew_MOD_damch(int *iaa, int *ia);
  void __dabnew_MOD_dadcd(int *jj, int *ic1, int *ic2);
  void __dabnew_MOD_dancd(int *ic1, int *ic2, int *jj);
  void __dabnew_MOD_datra(int *idif, int *ina, int *inc);
  void __dabnew_MOD_hash(int *no1, int *nv1, int *jj, int *ic1, int *ic2);
  void __dabnew_MOD_dehash(int *no1, int *nv1, int *ic1, int *ic2, int *jj);
  void __dabnew_MOD_daran(int *ina, double *cm, double *xran);
  void __dabnew_MOD_dacycle(int *ina, int *ipresent, double *value, int *illa, int *j);
  void __dabnew_MOD_daclean(int *ina, double *value);
