#!/usr/bin/env lua

-- Init
require"core.init"

-- Handle args
local options = require"core.options"
options.processOptions(arg)

-- Do tests if applicable
if options.utest then
	require"core.unitTest"()
end

-- Exec
require"core.exec"(options)

-- Fini
require"core.fini"
